services:
  postgres:
    image: postgres:latest
    container_name: postgres-currency-converter
    environment:
      POSTGRES_DB: Converter
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    ports:
      - "0000:0000"
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: unless-stopped

volumes:
  postgres_data:
