CREATE TABLE currencies
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code           VARCHAR(3)                              NOT NULL,
    name           VARCHAR(255)                            NOT NULL,
    name_ru        VARCHAR(255)                            NOT NULL,
    symbol         VARCHAR(10)                             NOT NULL,
    decimal_places SMALLINT                                NOT NULL,
    active         BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_currencies PRIMARY KEY (id)
);