spring.application.name=Converter

# ================== PostgreSQL ==================
spring.datasource.url= your_url
spring.datasource.username=your_username
spring.datasource.password=your_password

# ================== Flyway ==================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.validate-on-migrate=true
spring.flyway.clean-disabled=false

# ================== JPA ==================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ================== Logging ==================
logging.file.name=logs/converter.log
logging.level.root=WARN
logging.level.com.example.fruit.converter=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n

logging.logback.rollingpolicy.file-name-pattern=logs/converter.%d{yyyy-MM-dd}.%i.log
logging.logback.rollingpolicy.max-history=14
logging.logback.rollingpolicy.max-file-size=10MB