CREATE TABLE exchange_rates
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    base_currency   BIGINT                                  NOT NULL,
    target_currency BIGINT                                  NOT NULL,
    rate            DECIMAL(18, 8)                          NOT NULL,
    fetched_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    expires_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_exchange_rates PRIMARY KEY (id)
);

ALTER TABLE exchange_rates
    ADD CONSTRAINT uq_exchange_rates_pair UNIQUE (base_currency, target_currency);

ALTER TABLE exchange_rates
    ADD CONSTRAINT FK_EXCHANGE_RATES_ON_BASE_CURRENCY FOREIGN KEY (base_currency) REFERENCES currencies (id);

ALTER TABLE exchange_rates
    ADD CONSTRAINT FK_EXCHANGE_RATES_ON_TARGET_CURRENCY FOREIGN KEY (target_currency) REFERENCES currencies (id);